CREATE DATABASE UPLOAD_DOWNLOAD_DELETE;

USE UPLOAD_DOWNLOAD_DELETE;

create table MYFILES (
MYFILES_ID INT PRIMARY KEY AUTO_INCREMENT,
MYFILES_FILENAME VARCHAR(30) NOT NULL,
MYFILES_FILE longblob NOT NULL
)

